/* eslint-disable no-console */
const config = require('./config');

const swaggerAutogen = require('./app/swagger/swagger-autogen');

const doc = {
  info: {
    version: '1.0.1',
    title: 'Prisma API',
    // eslint-disable-next-line max-len
    description:
      'Documentation automatically generated by the <b>prisma-swagger-autogen</b> module.',
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
  host: `${config.server.host.replace('http://', '')}:${config.server.port}`,
  basePath: config.api.apiRoutePrefix,
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
};

console.log(
  `Documenting for ${config.server.host}:${config.server.port}${config.api.apiRoutePrefix}`,
);
const handlers = require('./modules')();

const outputFile = './app/swagger/output/swagger_output.json';

const endpointRoutes = handlers.routes;

const semibasePath = handlers.routers;

swaggerAutogen()(outputFile, endpointRoutes, doc, semibasePath).then(generation => {
  if (generation.success) {
    console.log('All routes of application \n', Object.keys(generation.data.paths));
  }
});
